//! Build-time codegen: reporters-db reporters.json → Zig lookup tables.
//! Runs as a normal program during `zig build` (addRunArtifact); the core
//! library imports its output as the `reporters_tables` module. Strict by
//! design: unknown cite_types or dangling variation targets abort the build —
//! the data is an upstream contract, and silent skips would hide drift.
const std = @import("std");

const Ed = struct {
    abbrev: []const u8,
    name: []const u8,
    cite_type: []const u8,
};

const Match = struct {
    key: []const u8,
    edition: u32,
    is_variant: bool,
};

const cite_types = [_][]const u8{
    "federal",        "neutral",         "scotus_early", "specialty",
    "specialty_lexis", "specialty_west", "state",        "state_regional",
};

fn matchLessThan(_: void, a: Match, b: Match) bool {
    switch (std.mem.order(u8, a.key, b.key)) {
        .lt => return true,
        .gt => return false,
        .eq => {},
    }
    if (a.edition != b.edition) return a.edition < b.edition;
    // canonical (is_variant=false) sorts first so dedup keeps it
    return @intFromBool(a.is_variant) < @intFromBool(b.is_variant);
}

fn writeZigString(w: *std.Io.Writer, s: []const u8) !void {
    try w.writeByte('"');
    for (s) |c| switch (c) {
        '"' => try w.writeAll("\\\""),
        '\\' => try w.writeAll("\\\\"),
        '\n' => try w.writeAll("\\n"),
        '\t' => try w.writeAll("\\t"),
        '\r' => try w.writeAll("\\r"),
        else => if (c >= 0x20 and c < 0x7f)
            try w.writeByte(c)
        else
            try w.print("\\x{x:0>2}", .{c}),
    };
    try w.writeByte('"');
}

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;

    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 3) {
        std.debug.print("usage: {s} <reporters.json> <out.zig>\n", .{args[0]});
        return error.BadArgs;
    }

    const data = try std.Io.Dir.cwd().readFileAlloc(io, args[1], arena, .unlimited);
    const parsed = try std.json.parseFromSlice(std.json.Value, arena, data, .{});
    const root = parsed.value.object;

    var editions: std.ArrayListUnmanaged(Ed) = .empty;
    var matches: std.ArrayListUnmanaged(Match) = .empty;

    var series_it = root.iterator();
    while (series_it.next()) |series| {
        for (series.value_ptr.array.items) |entry_val| {
            const entry = entry_val.object;
            const name = entry.get("name").?.string;
            const cite_type = entry.get("cite_type").?.string;

            const known = for (cite_types) |ct| {
                if (std.mem.eql(u8, ct, cite_type)) break true;
            } else false;
            if (!known) {
                std.debug.print("unknown cite_type '{s}' for '{s}'\n", .{ cite_type, name });
                return error.UnknownCiteType;
            }

            // editions of this entry: global table append + local index for
            // resolving this entry's variations
            var local: std.StringHashMapUnmanaged(u32) = .empty;
            var ed_it = entry.get("editions").?.object.iterator();
            while (ed_it.next()) |ed| {
                const idx: u32 = @intCast(editions.items.len);
                try editions.append(arena, .{
                    .abbrev = ed.key_ptr.*,
                    .name = name,
                    .cite_type = cite_type,
                });
                try local.put(arena, ed.key_ptr.*, idx);
                try matches.append(arena, .{ .key = ed.key_ptr.*, .edition = idx, .is_variant = false });
            }

            if (entry.get("variations")) |variations| {
                var var_it = variations.object.iterator();
                while (var_it.next()) |v| {
                    const target = v.value_ptr.string;
                    const idx = local.get(target) orelse {
                        std.debug.print(
                            "variation '{s}' -> '{s}' has no such edition in entry '{s}'\n",
                            .{ v.key_ptr.*, target, name },
                        );
                        return error.DanglingVariation;
                    };
                    try matches.append(arena, .{ .key = v.key_ptr.*, .edition = idx, .is_variant = true });
                }
            }
        }
    }

    std.mem.sort(Match, matches.items, {}, matchLessThan);

    var aw: std.Io.Writer.Allocating = .init(arena);
    const w = &aw.writer;

    try w.writeAll(
        \\// Generated by tools/gen_tables.zig from data/reporters_db/reporters.json — DO NOT EDIT.
        \\pub const CiteType = enum {
        \\
    );
    for (cite_types) |ct| try w.print("    {s},\n", .{ct});
    try w.writeAll(
        \\};
        \\
        \\pub const Edition = struct {
        \\    abbrev: []const u8,
        \\    reporter_name: []const u8,
        \\    cite_type: CiteType,
        \\};
        \\
        \\pub const MatchEntry = struct {
        \\    key: []const u8,
        \\    edition: u32,
        \\    is_variant: bool,
        \\};
        \\
        \\pub const editions: []const Edition = &.{
        \\
    );
    for (editions.items) |ed| {
        try w.writeAll("    .{ .abbrev = ");
        try writeZigString(w, ed.abbrev);
        try w.writeAll(", .reporter_name = ");
        try writeZigString(w, ed.name);
        try w.print(", .cite_type = .{s} }},\n", .{ed.cite_type});
    }
    try w.writeAll(
        \\};
        \\
        \\pub const match_table: []const MatchEntry = &.{
        \\
    );
    var emitted: usize = 0;
    var prev: ?Match = null;
    for (matches.items) |m| {
        // dedup exact (key, edition) repeats — canonical-first sort order
        // guarantees the kept one is the canonical spelling when both exist
        if (prev) |p| {
            if (std.mem.eql(u8, p.key, m.key) and p.edition == m.edition) continue;
        }
        prev = m;
        try w.writeAll("    .{ .key = ");
        try writeZigString(w, m.key);
        try w.print(", .edition = {d}, .is_variant = {} }},\n", .{ m.edition, m.is_variant });
        emitted += 1;
    }
    try w.writeAll("};\n");

    const out = try std.Io.Dir.cwd().createFile(io, args[2], .{});
    defer out.close(io);
    try out.writeStreamingAll(io, aw.written());
}
