//! Build-time codegen: courts-db courts.json → Zig court-resolution table.
//! Mirrors eyecite get_court_by_paren preprocessing: citation_string with
//! all non-\w characters stripped, lowercased, in file order (order matters:
//! eyecite returns the LAST startswith match when no exact match exists).
//! Strict: non-ASCII in a citation_string aborts (Python's \w is
//! unicode-aware; revisit normalization if upstream ever ships non-ASCII).
const std = @import("std");

fn writeZigString(w: *std.Io.Writer, s: []const u8) !void {
    try w.writeByte('"');
    for (s) |c| switch (c) {
        '"' => try w.writeAll("\\\""),
        '\\' => try w.writeAll("\\\\"),
        else => if (c >= 0x20 and c < 0x7f)
            try w.writeByte(c)
        else
            try w.print("\\x{x:0>2}", .{c}),
    };
    try w.writeByte('"');
}

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;

    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 3) {
        std.debug.print("usage: {s} <courts.json> <out.zig>\n", .{args[0]});
        return error.BadArgs;
    }

    const data = try std.Io.Dir.cwd().readFileAlloc(io, args[1], arena, .unlimited);
    const parsed = try std.json.parseFromSlice(std.json.Value, arena, data, .{});

    var aw: std.Io.Writer.Allocating = .init(arena);
    const w = &aw.writer;

    try w.writeAll(
        \\// Generated by tools/gen_courts.zig from courts-db — DO NOT EDIT.
        \\pub const Court = struct {
        \\    /// citation_string stripped of non-word chars, lowercased
        \\    norm: []const u8,
        \\    id: []const u8,
        \\};
        \\
        \\pub const courts: []const Court = &.{
        \\
    );

    var count: usize = 0;
    for (parsed.value.array.items) |item| {
        const obj = item.object;
        const cite_str = obj.get("citation_string").?.string;
        const id = obj.get("id").?.string;

        var norm: std.ArrayListUnmanaged(u8) = .empty;
        var i: usize = 0;
        while (i < cite_str.len) : (i += 1) {
            const c = cite_str[i];
            if (c >= 0x80) {
                // U+2019 (‘Dep’t’) is punctuation — Python \w strips it too.
                // Anything else non-ASCII is upstream drift: abort loudly.
                if (std.mem.startsWith(u8, cite_str[i..], "\xe2\x80\x99")) {
                    i += 2;
                    continue;
                }
                std.debug.print(
                    "non-ASCII citation_string '{s}' (id {s}) — normalization rules need review\n",
                    .{ cite_str, id },
                );
                return error.NonAsciiCitationString;
            }
            if (std.ascii.isAlphanumeric(c) or c == '_') {
                try norm.append(arena, std.ascii.toLower(c));
            }
        }
        if (norm.items.len == 0) continue; // can never match a non-empty query

        try w.writeAll("    .{ .norm = ");
        try writeZigString(w, norm.items);
        try w.writeAll(", .id = ");
        try writeZigString(w, id);
        try w.writeAll(" },\n");
        count += 1;
    }
    try w.writeAll("};\n");

    if (count == 0) return error.EmptyCourtsTable;

    const out = try std.Io.Dir.cwd().createFile(io, args[2], .{});
    defer out.close(io);
    try out.writeStreamingAll(io, aw.written());
}
